spring:
  datasource:
    url: jdbc:mysql://walkon-prd-rds-mysql-read01.c4xlnu8ouvmq.ap-northeast-2.rds.amazonaws.com/walkon?serverTimezone=Asia/Seoul
    username: walkon
    password: superwallaby
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    generate-ddl: false
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true